avatar:
  enable: true
  url: /images/3.jpg
  rounded: true
  opacity: 1
  mickey_mouse: true
  status:
    enable: true
    emoji: ğŸ˜Š
    message: ä¸æƒ³ä¸Šå­¦

colors:
  primary: '#6200ee'
  # bg: "#F5F5F5"
  selection_bg: '#8e71c1' # é€‰å–æ–‡å­—æ—¶çš„èƒŒæ™¯è‰²
  # æ ‡ç­¾äº‘ä¸­æ ‡ç­¾çš„èµ·å§‹è‰²å’Œç»“æŸè‰²
  # tag_start_color:
  # tag_end_color:

tags:
  Vue: '#4fc08d'
  Hexo: '#0E834D'
  CSS: '#5298d1'
  Node.js: '#026E00'
  Git: '#F14E32'
  React: '#61dafb'
  Python: '#3776ab'
  PHP: '#8892BF'
  VS Code: '#0066B8'
  JavaScript: '#F4DF4F'
  TypeScript: '#317AC6'
  Laravel: '#F4645F'

categories:
  ç¬”è®°: dimgray


head:
  js:
    async:
      # è¿™é‡Œæ˜¯ä½ ä» iconfont å¤„è·å¾—çš„å›¾æ ‡é“¾æ¥ã€‚
      iconfont: //at.alicdn.com/t/font_1140697_dxory92pb0h.js

social:
  - name: GitHub
    link: https://github.com/Kiritoabc
    icon: ri:github-line
    color: '#181717'
  - name: E-Mail
    link: 2493381254@qq.com
    icon: ri:mail-line
    color: '#8E71C1'
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=583001071
    icon: ri:netease-cloud-music-line
    color: '#C10D0C'
  - name: å“”å“©å“”å“©åŠ¨ç”»
    link: https://space.bilibili.com/160107797
    icon: ri:bilibili-line
    color: '#FF8EB3'

banner:
  enable: true
  title: è èçš„å°ç«™
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

mode: auto

font:
  cdn:
    enable: true
    lib:
      - https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@900&display=swap
  serif:
    family: '''Songti SC'', ''Noto Serif SC'', STZhongsong, STKaiti, KaiTi, Roboto, serif'
    weight: 900
  sans_serif:
    family: '''PingFang SC'', ''Microsoft YaHei'', Roboto, Arial, sans-serif'
    weight: 400
  monospace:
    family: '''Source Code Pro'', ''Courier New'', Courier, Consolas, Monaco, monospace'


fireworks:
  enable: true
  colors:
    - '102, 167, 221'
    - '62, 131, 225'
    - '33, 78, 194'


# _config.yun.yml
medium_zoom: true

cursor:
  enable: false
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur

sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line

  custom:
    title: æ–‡æ¡£
    path: https://yun.yunyoujun.cn
    icon: ri:settings-line

pages:
  - name: æˆ‘çš„å°ä¼™ä¼´ä»¬
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue

post_card:
  opacity: 0.8

types:
  link:
    color: blue
    icon: ri:external-link-line
  bilibili:
    color: '#FF8EB3'
    icon: ri:bilibili-line
  douban:
    color: '#007722'
    icon: ri:douban-line
  github:
    color: black
    icon: ri:github-line
  netease-cloud-music:
    color: '#C10D0C'
    icon: ri:netease-cloud-music-line
  notion:
    color: black
    icon: ri:notion
  twitter:
    color: '#1da1f2'
    icon: ri:twitter-line
  wechat:
    color: '#1AAD19'
    icon: ri:wechat-2-line
  weibo:
    color: '#E6162D'
    icon: ri:weibo-line
  yuque:
    color: '#25b864'
    icon: ant-design:yuque-outlined
  zhihu:
    color: '#0084FF'
    icon: ri:zhihu-line

codeblock:
  copy_btn: true


lazyload:
  enable: true

footer:
  since: 2023
  icon:
    name: ri:cloud-line
    animated: true
    color: '#0078E7'
  powered:
    enable: true
  ive_time:
    enable: false
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: '2023-10-12T00:00:00'

say:
  enable: true
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn

mourn:
  enable: true
  days:
    - 4-4

wordcloud:
  enable: true

girls:
  enable: true

wordcount:
  enable: true
  count: true
  time: true

url: https://Kiritoabc.github.io

post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true


vendors:
  waline:
    js: "@waline/client@v2/dist/waline.js"

#baidu_push: true

#iconify:
#  global: true
#
#local_search:
#  enable: true
#
#engine_search:
#  enable: false
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''
