menu:
  æ–‡ç« :
    éš§é“: /archives/ || anzhiyu-icon-box-archive
    åˆ†ç±»: /categories/ || anzhiyu-icon-shapes
    æ ‡ç­¾: /tags/ || anzhiyu-icon-tags

  å‹é“¾:
    å‹äººå¸: /link/ || anzhiyu-icon-link
    æœ‹å‹åœˆ: /fcircle/ || anzhiyu-icon-artstation
    ç•™è¨€æ¿: /comments/ || anzhiyu-icon-envelope

  æˆ‘çš„:
    éŸ³ä¹é¦†: /music/ || anzhiyu-icon-music
    è¿½ç•ªé¡µ: /bangumis/ || anzhiyu-icon-bilibili
    ç›¸å†Œé›†: /album/ || anzhiyu-icon-images
    å°ç©ºè°ƒ: /air-conditioner/ || anzhiyu-icon-fan

  å…³äº:
    å…³äºæœ¬äºº: /about/ || anzhiyu-icon-paper-plane
    é—²è¨€ç¢è¯­: /essay/ || anzhiyu-icon-lightbulb
    éšä¾¿é€›é€›: javascript:toRandomPost() || anzhiyu-icon-shoe-prints1

# navç›¸å…³é…ç½®
nav:
  enable: false
  travelling: false
  clock: true
  menu:
    - title: ç½‘é¡µ
      item:
        - name: åšå®¢
          link: https://blog.anheyu.com/
          icon: /img/favicon.png
    - title: é¡¹ç›®
      item:
        - name: å®‰çŸ¥é±¼å›¾åºŠ
          link: https://image.anheyu.com/
          icon: https://image.anheyu.com/favicon.ico


highlight_theme: light
highlight_copy: true
highlight_shrink: true #ä»£ç æ¡†ä¸å±•å¼€ï¼Œéœ€ç‚¹å‡» '>' æ‰“å¼€
code_word_wrap: true
highlight_height_limit: false # unit: px


icons:
  ali_iconfont_js: https://www.iconfont.cn/collections/detail?cid=44481 # é˜¿é‡Œå›¾æ ‡symbol å¼•ç”¨é“¾æ¥ï¼Œä¸»é¢˜ä¼šè¿›è¡ŒåŠ è½½ symbol å¼•ç”¨
  fontawesome: false #æ˜¯å¦å¯ç”¨fontawesome6å›¾æ ‡
  fontawesome_animation_css: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@1.0.17/lib/assets/font-awesome-animation.min.css #fontawesome_animation å¦‚æœæœ‰å°±ä¼šåŠ è½½ï¼Œç¤ºä¾‹å€¼ï¼šhttps://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@1.0.17/lib/assets/font-awesome-animation.min.css


  # social settings (ç¤¾äº¤å›¾æ ‡è®¾ç½®)
  # formal:
  #   name: link || icon
  social:
   Github: https://github.com/Kiritoabc
   BiliBili: https://space.bilibili.com/160107797?spm_id_from=333.1007.0.0

# ä½œè€…å¡ç‰‡ çŠ¶æ€
author_status:
  enable: true
  # å¯ä»¥æ˜¯ä»»ä½•å›¾ç‰‡ï¼Œå»ºè®®æ”¾è¡¨æƒ…åŒ…æˆ–è€…emojiå›¾ç‰‡ï¼Œæ•ˆæœéƒ½å¾ˆå¥½ï¼Œ[è¡¨æƒ…åŒ…é€ŸæŸ¥](https://emotion.xiaokang.me/)
  statusImg: "https://bu.dusays.com/2023/08/24/64e6ce9c507bb.png"
  skills:
    - ğŸ¤–ï¸ æ•°ç ç§‘æŠ€çˆ±å¥½è€…
    - ğŸ” åˆ†äº«ä¸çƒ­å¿ƒå¸®åŠ©
    - ğŸ  æ™ºèƒ½å®¶å±…å°èƒ½æ‰‹
    - ğŸ”¨ è®¾è®¡å¼€å‘ä¸€æ¡é¾™
    - ğŸ¤ ä¸“ä¿®äº¤äº’ä¸è®¾è®¡
    - ğŸƒ è„šè¸å®åœ°è¡ŒåŠ¨æ´¾
    - ğŸ§± å›¢é˜Ÿå°ç»„å‘åŠ¨æœº
    - ğŸ’¢ å£®æ±‰äººç‹ è¯ä¸å¤š


# Footer Settings
# --------------------------------------
footer:
  owner:
    enable: true
    since: 2020
  custom_text:
  runtime:
    enable: true
    launch_time: 04/01/2022 00:00:00 # ç½‘ç«™ä¸Šçº¿æ—¶é—´
    work_img: https://npm.elemecdn.com/anzhiyu-blog@2.0.4/img/badge/å®‰çŸ¥é±¼-ä¸Šç­æ‘¸é±¼ä¸­.svg
    work_description: è·ç¦»æœˆå…¥25kä¹Ÿå°±è¿˜å·®ä¸€ä¸ªå¤§ä½¬å¸¦æˆ‘~
    offduty_img: https://npm.elemecdn.com/anzhiyu-blog@2.0.4/img/badge/å®‰çŸ¥é±¼-ä¸‹ç­å•¦.svg
    offduty_description: ä¸‹ç­äº†å°±è¯¥å¼€å¼€å¿ƒå¿ƒçš„ç©è€ï¼Œå˜¿å˜¿~
  # å¾½æ ‡éƒ¨åˆ†é…ç½®é¡¹ https://shields.io/
  # https://img.shields.io/badge/CDN-jsDelivr-orange?style=flat&logo=jsDelivr
  bdageitem:
    - link: https://hexo.io/ #å¾½æ ‡æŒ‡å‘ç½‘ç«™é“¾æ¥
      shields: https://npm.elemecdn.com/anzhiyu-blog@2.1.5/img/badge/Frame-Hexo.svg #å¾½æ ‡API
      message: åšå®¢æ¡†æ¶ä¸ºHexo_v5.4.0 #å¾½æ ‡æç¤ºè¯­
    - link: https://blog.anheyu.com/
      shields: https://pan.anheyu.com/d/anzhiyu/svg/Theme-AnZhiYu-2E67D3.svg
      message: æœ¬ç«™ä½¿ç”¨AnZhiYuä¸»é¢˜
    - link: https://www.dogecloud.com/
      shields: https://npm.elemecdn.com/anzhiyu-blog@2.2.0/img/badge/CDN-å¤šå‰äº‘-3693F3.svg
      message: æœ¬ç«™ä½¿ç”¨å¤šå‰äº‘ä¸ºé™æ€èµ„æºæä¾›CDNåŠ é€Ÿ
    - link: https://github.com/
      shields: https://npm.elemecdn.com/anzhiyu-blog@2.1.5/img/badge/Source-Github.svg
      message: æœ¬ç«™é¡¹ç›®ç”±Githubæ‰˜ç®¡
    - link: http://creativecommons.org/licenses/by-nc-sa/4.0/
      shields: https://npm.elemecdn.com/anzhiyu-blog@2.2.0/img/badge/Copyright-BY-NC-SA.svg
      message: æœ¬ç«™é‡‡ç”¨çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº«4.0å›½é™…è®¸å¯åè®®è¿›è¡Œè®¸å¯


cover:
  # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« å°é¢
  index_enable: true
  aside_enable: true
  archives_enable: true
  # å°é¢æ˜¾ç¤ºçš„ä½ç½®
  # ä¸‰ä¸ªå€¼å¯é…ç½® left , right , both
  position: both
  # å½“æ²¡æœ‰è®¾ç½®coveræ—¶ï¼Œé»˜è®¤çš„å°é¢æ˜¾ç¤º
  default_cover:
    - https://c-ssl.duitang.com/uploads/blog/202205/21/20220521005109_e610d.jpeg
    - https://file.crazywong.com/gh/jerryc127/CDN@latest/cover/default_bg.png
    - https://file.crazywong.com/gh/jerryc127/CDN@latest/cover/default_bg2.png
    - https://file.crazywong.com/gh/jerryc127/CDN@latest/cover/default_bg3.png


post_meta:
  page:
    date_type: both # created or updated or both ä¸»é¡µæ–‡ç« æ—¥æœŸæ˜¯åˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½æ˜¾ç¤º
    date_format: relative # date/relative æ˜¾ç¤ºæ—¥æœŸè¿˜æ˜¯ç›¸å¯¹æ—¥æœŸ
    categories: true # true or false ä¸»é¡µæ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
    tags: true # true or false ä¸»é¡µæ˜¯å¦æ˜¾ç¤ºæ ‡ç­¾
    label: true # true or false æ˜¾ç¤ºæè¿°æ€§æ–‡å­—
  post:
    date_type: both # created or updated or both æ–‡ç« é¡µæ—¥æœŸæ˜¯åˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½æ˜¾ç¤º
    date_format: relative # date/relative æ˜¾ç¤ºæ—¥æœŸè¿˜æ˜¯ç›¸å¯¹æ—¥æœŸ
    categories: true # true or false æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
    tags: true # true or false æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºæ ‡ç­¾
    label: true # true or false æ˜¾ç¤ºæè¿°æ€§æ–‡å­—

post_copyright:
  enable: true
  decode: false
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

reward:
  enable: true
  coinAudio: https://npm.elemecdn.com/akilar-candyassets@1.0.36/audio/aowu.m4a
  QR_code:
    - img: https://npm.elemecdn.com/anzhiyu-blog@1.1.6/img/post/common/qrcode-weichat.png
      link:
      text: wechat
    - img: https://npm.elemecdn.com/anzhiyu-blog@1.1.6/img/post/common/qrcode-alipay.png
      link:
      text: alipay
toc:
  post: true
  page: true
  number: true
  expand: false
  style_simple: false # for post

related_post:
  enable: true
  limit: 6 # æ˜¾ç¤ºæ¨èæ–‡ç« æ•°ç›®
  date_type: created # or created or updated æ–‡ç« æ—¥æœŸæ˜¾ç¤ºåˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥



# Displays outdated notice for a post (æ–‡ç« è¿‡æœŸæé†’)
noticeOutdate:
  enable: true
  style: flat # style: simple/flat
  limit_day: 365 # When will it be shown
  position: top # position: top/bottom
  message_prev: It has been
  message_next: days since the last update, the content of the article may be outdated.

# ä¸­æ§å°
centerConsole: true

# A simple 404 page
error_404:
  enable: true
  subtitle: "é¡µé¢æ²¡æœ‰æ‰¾åˆ°"
  background: